django_school_roster_proj/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

# app_name = 'school'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('school/', include('school_roster_app.urls'))
]

school_roster_app/urls.py
from django.urls import path
from . import views

app_name = 'school'
urlpatterns = [
    path('', views.index, name='home'),
    path("staff/", views.list_staff, name="list_staff"),
    path("staff/<int:employee_id>/", views.staff_detail, name="staff_detail"),
    path("students/", views.list_students, name="list_students"),
    path("students/<int:student_id>/", views.student_detail, name="student_detail"),

]

school_roster_app/models.py
from django.db import models

# Create your models here.
import os.path
import json


class School:
    def __init__(self, name):
        self.name = name
        self.staff = Staff.load_all()
        self.students = Student.load_all()

    def find_student_by_id(self, school_id):
        for student in self.students:
            if student.school_id == school_id:
                return student
        
        return None

    def find_staff_by_id(self, employee_id):
        for staff in self.staff:
            if staff.employee_id == employee_id:
                return staff
        
        return None

class Person:

    def __init__(self, name, age, password, role):
        self.name = name
        self.age = age
        self.password = password
        self.role = role

    @classmethod
    def load_all(cls):
        my_path = os.path.abspath(os.path.dirname(__file__))
        file_path = os.path.join(my_path, cls.DATA_FILE)
        
        people = []
        
        f = open(file_path)
        data = json.load(f)
        for i in data:
            people.append(cls(**dict(i)))
            

        return people
        





class Staff(Person):
    DATA_FILE = "../data/staff.json"

    def __init__(self, name, age, password, role, employee_id):
        super().__init__(name, age, password, role)
        self.employee_id = employee_id

    def __repr__(self):
        return f"staff: {self.name}"



class Student(Person):
    DATA_FILE = "../data/students.json"

    def __init__(self, name, age, password, role, school_id):
        super().__init__(name, age, password, role)
        self.school_id = school_id

    def __str__(self):
        return f"{self.name.upper()}\n--------------\nage: {self.age}\nid: {self.school_id}"

school_roster_app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import School # import our School class
from django.http import HttpResponse

my_school = School("Django School") # create a school instance


def index(request):
    my_data = { 
        "school_name": my_school.name
    }
    return render(request, "pages/index.html", my_data)



def list_staff(request):
    my_data = {
        "staff_list" : my_school.staff
        }
    return render(request, 'pages/staff.html', my_data)

def staff_detail(request, employee_id):
    employee = ''
    for member in my_school.staff:
        if member.employee_id == int(employee_id):
            employee = member
    return render(request, 'pages/staff_detail.html', {'employee' : employee})


def list_students(request):
    my_data = {
        "students_list" : my_school.students
    }
    return render(request, 'pages/students.html', my_data)


def student_detail(request, student_id):
    student = ''
    for member in my_school.students:
        if member.school_id == int(student_id):
            student = member
    return render(request, 'pages/student_detail.html', {'student' : student})

school_roster_app/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>School</title>
</head>
<body>
    
    <h2>{{ school_name }} Directory</h2>


    <ul>
        <li><a href="{% url 'school:list_staff' %}">All Staff</a></li>
        <li><a href="{% url 'school:list_students' %}">All Students</a></li>
    </ul>
</body>
</html>

school_roster_app/templates/pages/staff.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff List</title>
</head>

<body>
    <h1>Staff List</h1>    
    {% for person in staff_list %}
        <ul>
            <!-- <h1>{{ person.employee_id }}</h1> -->
            <li><a href="{% url 'school:staff_detail' person.employee_id %}">{{ person.name }}</a></li>
            <!-- <li>{{ person.name }}</li> -->
        </ul>
    {% endfor %}
</body>
</html>

school_roster_app/templates/pages/staff_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff Detail</title>
</head>
<body>
    <h1>Staff Detail</h1>

    <ul>    
        <li>Name: {{ employee.name }}</li>
        <li>Age: {{ employee.age }}</li>
        <li>Role: {{ employee.role }}</li>
        <li>ID: {{ employee.employee_id }}</li>
        <li>Password: {{ employee.password }}</li>
        
    </ul>
</body>
</html>

school_roster_app/templates/pages/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Detail</title>
</head>
<body>
    <ul>
        <li>Name: {{ student.name }}</li>
        <li>Age: {{ student.age }}</li>
        <li>Role: {{ student.role }}</li>
        <li>ID: {{ student.school_id }}</li>
        <li>Password {{ student.password }}</li>
    </ul>
    
</body>
</html>

school_roster_app/templates/pages/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Students List</title>
</head>
<body>
    <h1>Students List</h1>
    {% for student in students_list %}
    <ul>
        <li><a href="{% url 'school:student_detail' student.school_id %}"> {{ student.name }} </a></li>
        <!-- <li> {{ student.name }} </li> -->
    </ul>
    {% endfor %}
</body>
</html>